export const API_URL = "API_URL";
export const API_ENDPOINT_LIST = "API_ENDPOINT_LIST";
export const API_ENDPOINT_SINGLE = "API_ENDPOINT_SINGLE";
export const API_ENDPOINT_CREATE = "API_ENDPOINT_CREATE";
export const API_ENDPOINT_UPDATE = "API_ENDPOINT_UPDATE";
export const API_ENDPOINT_DELETE = "API_ENDPOINT_DELETE";
export const API_ENTRIES_PER_PAGE = "API_ENTRIES_PER_PAGE";

export const API_LIST_REQUEST_IN_PROGRESS = "API_LIST_REQUEST_IN_PROGRESS";
export const API_LIST_REQUEST_ERROR = "API_LIST_REQUEST_ERROR";
export const API_LIST_REQUEST_ERROR_MESSAGE = "API_LIST_REQUEST_ERROR_MESSAGE";

export const API_USER_REQUEST_IN_PROGRESS = "API_USER_REQUEST_IN_PROGRESS";
export const API_USER_REQUEST_ERROR = "API_USER_REQUEST_ERROR";
export const API_USER_REQUEST_ERROR_MESSAGE = "API_USER_REQUEST_ERROR_MESSAGE";

export const API_USER_UPDATE_REQUEST_IN_PROGRESS =
  "API_USER_UPDATE_REQUEST_IN_PROGRESS";
export const API_USER_UPDATE_REQUEST_ERROR = "API_USER_UPDATE_REQUEST_ERROR";
export const API_USER_UPDATE_REQUEST_ERROR_MESSAGE =
  "API_USER_UPDATE_REQUEST_ERROR_MESSAGE";

export const API_USER_CREATE_REQUEST_IN_PROGRESS =
  "API_USER_CREATE_REQUEST_IN_PROGRESS";
export const API_USER_CREATE_REQUEST_ERROR = "API_USER_CREATE_REQUEST_ERROR";
export const API_USER_CREATE_REQUEST_ERROR_MESSAGE =
  "API_USER_CREATE_REQUEST_ERROR_MESSAGE";

export default {
  [API_URL]: "https://reqres.in",
  [API_ENDPOINT_LIST]: "/api/users",
  [API_ENDPOINT_SINGLE]: "/api/users",
  [API_ENDPOINT_CREATE]: "/api/users",
  [API_ENDPOINT_UPDATE]: "/api/users",
  [API_ENDPOINT_DELETE]: "/api/users",
  [API_ENTRIES_PER_PAGE]: 8,

  [API_LIST_REQUEST_IN_PROGRESS]: false,
  [API_LIST_REQUEST_ERROR]: false,
  [API_LIST_REQUEST_ERROR_MESSAGE]: null,

  [API_LIST_REQUEST_IN_PROGRESS]: false,
  [API_LIST_REQUEST_ERROR]: false,
  [API_LIST_REQUEST_ERROR_MESSAGE]: null,

  [API_USER_UPDATE_REQUEST_IN_PROGRESS]: false,
  [API_USER_UPDATE_REQUEST_ERROR]: false,
  [API_USER_UPDATE_REQUEST_ERROR_MESSAGE]: false,

  [API_USER_CREATE_REQUEST_IN_PROGRESS]: false,
  [API_USER_CREATE_REQUEST_ERROR]: false,
  [API_USER_CREATE_REQUEST_ERROR_MESSAGE]: false
};
